apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: institutional-defi

resources:
  - namespace.yaml
  - service-account.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - api-service.yaml
  - regulatory-workbench-deployment.yaml
  - regulatory-workbench-service.yaml
  - external-secret.yaml
  - hpa-api.yaml
  - hpa-worker.yaml
  - pdb-api.yaml
  - pdb-worker.yaml
  - egress-common.yaml

commonLabels:
  app.kubernetes.io/part-of: institutional-defi-platform
  app.kubernetes.io/managed-by: kustomize
