apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: institutional-defi-dev

resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml
  - egress-app.yaml

nameSuffix: -dev

replicas:
  - name: api
    count: 1
  - name: worker
    count: 1

images:
  - name: institutional-defi-api
    newName: 547729607601.dkr.ecr.us-east-1.amazonaws.com/institutional-defi-api
    newTag: latest
  - name: institutional-defi-worker
    newName: 547729607601.dkr.ecr.us-east-1.amazonaws.com/institutional-defi-worker
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
    target:
      kind: HorizontalPodAutoscaler

commonLabels:
  environment: dev
